[server]
address = "0.0.0.0:4000"
read_time_out = 10
write_time_out = 20

[redis]
redis_url = "localhost:6379"
redis_cert = ""
redis_idle_timeout = 4
redis_db_num = 0

[mqtt]
mqtt_broker = "tcp://broker.emqx.io:1883"
topic = "speed_topic"